INPDR-Server_withAPI/config/routes.rb
Rails.application.routes.draw do

  mount API::Base => "/"

  match '/contacts', :to => 'contacts#new', :via => 'get'
  resources :contacts, :only => [:new, :create]

  devise_for :users, :controllers => {:registrations => :registrations}

  root :to => 'pages#index'

  get 'pages/index'
  get 'pages/registration'
  get 'pages/terms_and_conditions'
  get 'pages/privacy_statement'
  get 'pages/followups'
  get 'pages/verifications'
  get 'pages/thank_enrol'

  post 'patients/consent_action', to: 'patients#consent_action'
  resources :patients do
    get 'enrol'
    get 'verify', :on => :member
    resources :npa_applicant_participants do
    end

    resources :npb_participants do
      resources :npb_followups, :defaults => {:followable => 'npb_participants'}
    end

    resources :npb_applicant_participants do
      resources :npb_followups, :defaults => {:followable => 'npb_applicant_participants'}
    end

    resources :npc_applicant_participants do
      resources :npc_followups, :defaults => {:followable => 'npc_applicant_participants'}
    end

    resources :npc_participants do
      resources :npc_followups, :defaults => {:followable => 'npc_participants'}
    end
  end

end

INPDR-Server_withAPI/app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user

  belongs_to :enrollable, polymorphic: true

  validates_date :date_of_birth, :allow_nil => true, :on_or_before => lambda { Date.current }

  validates :registrant_first_name, :registrant_last_name, :presence => true

  has_one :address, as: :person, dependent: :destroy, validate: true

  accepts_nested_attributes_for :address

  has_one :specialist, as: :patient, :dependent => :destroy, :validate => true
  accepts_nested_attributes_for :specialist

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  def self.gender_collection
    [['Male', 0],
     ['Female', 1]]
  end

  def self.applicant_relation_collection
    [['Self', 0],
     ['Mother', 1],
     ['Father', 2],
     ['Guardian', 3],
     ['Husband', 4],
     ['Wife', 5],
     ['Partner', 6],
     ['Brother', 7],
     ['Sister', 8],
     ['Son', 9],
     ['Daughter', 10],
     ['Carer', 11],
     ['Other', 12]]
  end

  def validate_consent?
    !self.consent.nil? && !self.consent_name.blank?
  end

  def generate_unique_id
    self.unique_id = loop do
      random_number = SecureRandom.random_number(1000000)
      break random_number unless (Patient.exists?(:unique_id => random_number))
    end
  end

  def get_unique_id
    if defined? self.enrollable
      if ((self.enrollable.is_a? NpcParticipant) || (self.enrollable.is_a? NpcApplicantParticipant))
        "NPC-#{self.unique_id}"
      elsif ((self.enrollable.is_a? NpbParticipant) || (self.enrollable.is_a? NpbApplicantParticipant))
        "NPB-#{self.unique_id}"
      else
        "NPA-#{self.unique_id}"
      end
    else
      "#{self.registrant_first_name} #{self.registrant_last_name}"
    end
  end
end

INPDR-Server_withAPI/app/controllers/api/v1/patients.rb
module API
  module V1
    class Patients < Grape::API
      include API::V1::Defaults

      resource :patients do
        desc "Return all patients"
        get "", root: "patients" do
          @patients = policy_scope(Patient)
          present @patients, :with => API::Entities::Patients
        end

        desc "Return a Patient"
        params do
          requires :id, type: String, desc: "ID of the
            Patient"
        end
        get ":id", root: "patients" do
          @patients = Patient.where(id: permitted_params[:id])
          authorize @patients[0], :show? unless @patients.blank?
          present @patients, :with => API::Entities::Patients
        end

        desc "Return a Patient belongs to user"
        params do
          requires :user_id, type: String, desc: "user_id of the
            Patient"
        end

        # Use /patients
        # get "/user_id/:user_id", root: "patients" do
        #   @patient = Patient.where(user_id: permitted_params[:user_id])
        #   present @patient, :with => API::Entities::Patients
        # end
      end
    end
  end
end

INPDR-Server_withAPI/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, :only => [:show, :edit, :update, :destroy]

  def enrol
  end

  # GET /patients/consent
  def consent
    @patient = Patient.new(patient_params)
    authorize @patient
  end

  # POST /patients/consent_action
  def consent_action
    @patient = Patient.new(patient_params)
    authorize @patient
    @patient.user = current_user
    @patient.generate_unique_id
    respond_to do |format|
      if @patient.valid?
        if @patient.validate_consent? && @patient.save
          ParticipantMailer.enrolment_email(current_user.email).deliver_now
          format.html { redirect_to patient_enrol_path(@patient) }
          format.json { render :show, status: :created, location: @patient }
        else
          flash.now[:alert] = t('flash.alert.consent')
          format.html { render :consent }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      else
        @patient.populate
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /patients
  # GET /patients.json
  def index
    @user = current_user
    authorize Patient
    if @user.study_team
      @all_patients = Patient.all
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    authorize @patient
  end

  # GET /patients/new
  def new
    @patient = Patient.new
    authorize @patient
    @patient.build_address
    specialist = Specialist.new
    specialist.build_address
    @patient.specialist = specialist
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    authorize @patient
    @patient.user = current_user
    respond_to do |format|
      # if @patient.not_finish?
      #   if @patient.save(validate: false)
      #     format.html { redirect_to patients_path }
      #     format.json { render :show, status: :created, location: @patient }
      #   else
      #     format.html { render :new }
      #     format.json { render json: @patient.errors, status: :unprocessable_entity }
      #   end
      # else
        if @patient.valid?
          format.html { render :consent }
          format.json { render :consent }
        else
          format.html { render :new }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      # end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    authorize @patient
    @patient.user = current_user
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, :notice => 'Patient was successfully updated.' }
        format.json { render :show, :status => :ok, :location => @patient }
      else
        format.html { render :edit }
        format.json { render :json => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    authorize @patient
    respond_to do |format|
      format.html { redirect_to patients_url, :notice => 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /patients/1/verify
  # GET /patients/1/verify.json
  def verify
    @patient = Patient.find(params[:id])
    authorize @patient
    if !@patient.verified? && (defined? @patient.enrollable) && !@patient.enrollable.not_finish?
      @patient.verified = true
    end

    respond_to do |format|
      if @patient.save
        ParticipantMailer.verify_email(@patient).deliver_now
        format.html { redirect_to patients_path, notice: 'Successfully verified participant.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :show }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:registrant_first_name,
                                    :registrant_last_name,
                                    :relation_to_patient,
                                    {:address_attributes => [
                                        :_destroy,
                                        :line_1,
                                        :line_2,
                                        :town,
                                        :county,
                                        :post_code,
                                        :country
                                    ]},
                                    :patient_first_name,
                                    :patient_last_name,
                                    :gender,
                                    :date_of_birth,
                                    :consent,
                                    :consent_name,
                                    :not_finish,
                                    {:specialist_attributes => [:id,
                                                                 :name,
                                                                 :hospital_name,
                                                                 {:address_attributes => [
                                                                     :_destroy,
                                                                     :line_1,
                                                                     :line_2,
                                                                     :town,
                                                                     :county,
                                                                     :post_code,
                                                                     :country
                                                                 ]},
                                                                 :number,
                                                                 :email]})
  end
end

INPDR-Server_withAPI/app/helpers/patients_helper.rb
module PatientsHelper
end

INPDR-Server_withAPI/app/views/patients/_form.html.erb
<%= simple_form_for(@patient, :html => { :class => 'form-horizontal' },
                    :wrapper => :horizontal_input_group,
                    :wrapper_mappings => {
                        :check_boxes => :horizontal_radio_and_checkboxes,
                        :radio_buttons => :horizontal_radio_and_checkboxes,
                        :file => :horizontal_file_input,
                        :boolean => :horizontal_boolean
                    }) do |f| %>
    <%= f.error_notification %>

    <h1>Welcome to the International Niemann-Pick Disease Registry Project – Patient Reported Data Registry!</h1>

    <p>
      Niemann Pick Diseases (NPD) are rare, progressive conditions with many unanswered questions. More
      information is needed to better understand how they affect people and progress over time. The International
      Niemann Pick Disease Registry (INPDR) – a joint initiative between patient organisations and clinicians involved
      in the care of people with NPD – has been established to better understand NPD so that potential treatments
      can be developed as quickly as possible.
    </p>

    <p>
      There are two components to the INPDR, together collecting clinical, genetic, diagnostic and outcome data:
      patient reported data (PRD), completed by the patient or their carer if appropriate; and clinician reported data
      (CRD), completed by healthcare professionals caring for NPD patients.
    </p>

    <p>
      You can confidentially add health information in the patient-reported section of the INPDR. Only anonymous
      health information will be made accessible to qualified researchers who are granted permission by the
      steering committee. Personal health information will not be made available to employers, government
      organisations, insurance companies, or educational institutions. Please refer to the Privacy Policy for more
      information.
    </p>

    <p>
      We welcome all patients diagnosed with any type of NPD worldwide. Patients can participate in the registry
      regardless of whether or not they are involved in other clinical studies and trials.
    </p>

    <p>
      <strong>If you are registering more than one person</strong>, you may use the same login and password to enter
      multiple patients. However, a separate survey must be completed for each person. This can be done after
      registering by clicking "Add a new patient" from your log in page.
    </p>

    <p>
      Please feel free to share any questions or concerns with us! You can contact the INPDR team at
      <a href="mailto:inpdr@uhb.nhs.uk" target="_top">inpdr@uhb.nhs.uk</a>
    </p>

    <h2></h2>



    <div class='panel panel-primary'>
      <div class='panel-heading'>
        <h3 class='panel-title'>Registration</h3>
      </div>
      <div class='panel-body'>

        Thank you for taking the time to complete this information and assist in our efforts to improve the lives of
        those living with Niemann-Pick Diseases.

        <%= f.input :registrant_first_name, label: t("#{controller_name}.labels.registrant_first_name") %>
        <%= f.input :registrant_last_name, label: t("#{controller_name}.labels.registrant_last_name") %>
        <%= f.simple_fields_for :address do |address_form| %>
            <%= render 'layouts/address_fields', :f => address_form, :locals => { :need_validate => true } %>
        <% end %>
        <%= f.input :relation_to_patient, :collection => Patient.applicant_relation_collection, label: t("#{controller_name}.labels.relation_to_patient") %>
        <%= f.input :patient_first_name, label: t("#{controller_name}.labels.patient_first_name") %>
        <%= f.input :patient_last_name, label: t("#{controller_name}.labels.patient_last_name") %>
        <%= f.input :gender, collection: Patient.gender_collection, label: t("#{controller_name}.labels.gender") %>
        <%= f.input :date_of_birth, :label => t("#{controller_name}.labels.date_of_birth"), :as => :date_picker %>

        <p>
          Please provide the names and contact details of the <i>current</i> main specialists for Niemann-Pick Disease
        </p>
        <%= f.simple_fields_for :specialist do |specialist_form| %>
            <%= render 'layouts/specialist_fields', :f => specialist_form, :locals => { :need_validate => true } %>
        <% end %>

      </div>
    </div>

    <%= f.input :not_finish, :as => 'hidden', :input_html => { :value => false } %>
    <div class="form-actions pull-right">
      <!---->
      <!--<%= f.button :submit, t('button.save_for_later'), :class => 'btn btn-warning js-only', onclick: 'setPatientNotFinish(true)' %>-->
      <!---->
      <%= f.button :submit, 'Submit', :class => 'btn btn-success', onclick: 'setPatientNotFinish(false)' %>
    </div>
<% end %>

INPDR-Server_withAPI/app/views/patients/consent.html.erb
<div class="form_well">
  <%= simple_form_for(@patient,
                      :url => patients_consent_action_path,
                      :method => :post,
                      :html => {:class => 'form-horizontal'},
                      :wrapper => :horizontal_input_group,
                      :wrapper_mappings => {
                              :check_boxes => :horizontal_radio_and_checkboxes,
                              :radio_buttons => :horizontal_radio_and_checkboxes,
                              :file => :horizontal_file_input,
                              :boolean => :horizontal_boolean
                      }) do |f| %>
      <%= render 'layouts/consent_form', :f => f %>
      <div style='display:none;'>
        <%= render 'form', :f => f %>
      </div>

  <% end %>

  <div class="form-actions pull-right">
    <%= link_to 'Cancel', :back, :class => 'btn btn-danger' %>
  </div>
</div>

INPDR-Server_withAPI/app/views/patients/edit.html.erb
<%= render 'form' %>

<div class="form-actions pull-right">
  <%= link_to 'Cancel', :back, :class => 'btn btn-danger' %>
</div>

INPDR-Server_withAPI/app/views/patients/enrol.html.erb
<div class="center jumbotron">
  <h1><%= t '.title' %></h1>

  <div class="list-group">
    <a href="<%=  new_patient_npc_participant_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npc_title') %></h4>
      <p class="list-group-item-text"><%= t('.npc_details') %></p>
    </a>
    <a href="<%=  new_patient_npc_applicant_participant_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npc_behalf_title') %></h4>
      <p class="list-group-item-text"><%= t('.npc_behalf_details') %></p>
    </a>
    <a href="<%=  new_patient_npb_participant_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npb_title') %></h4>
      <p class="list-group-item-text"><%= t('.npb_details') %></p>
    </a>
    <a href="<%=  new_patient_npb_applicant_participant_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npb_behalf_title') %></h4>
      <p class="list-group-item-text"><%= t('.npb_behalf_details') %></p>
    </a>
    <a href="<%=  new_patient_npa_applicant_participant_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npa_title') %></h4>
      <p class="list-group-item-text"><%= t('.npa_details') %></p>
    </a>
  </div>

</div>

INPDR-Server_withAPI/app/views/patients/index.html.erb
<h1><%= t 'pages.home.title', :email => @user.email %></h1>

<h2><%= t 'pages.home.table_title' %></h2>
<table class='table table-condensed table-bordered table-striped'>
  <thead>
  <tr>
    <th class="col-md-2"><%= t 'patients.labels.registrant_first_name' %></th>
    <th class="col-md-2"><%= t 'patients.labels.registrant_last_name' %></th>
    <th class="col-md-2"><%= t 'patients.labels.relation_to_patient' %></th>
    <th class="col-md-2"><%= t 'patients.labels.patient_first_name' %></th>
    <th class="col-md-2"><%= t 'patients.labels.patient_last_name' %></th>
    <th class="col-md-1"></th>
    <th class="col-md-1"></th>
  </tr>
  </thead>
  <tbody>
  <% @user.patients.each do |patient| %>
      <% if patient.enrollable %>
          <% next unless patient.enrollable.not_finish? %>
          <tr>
            <td><%= patient.registrant_first_name %></td>
            <td><%= patient.registrant_last_name %></td>
            <td>
              <% if patient.relation_to_patient %>
                  <%= Patient.applicant_relation_collection[patient.relation_to_patient][0] %>
              <% end %>
            </td>
            <td><%= patient.patient_first_name %></td>
            <td><%= patient.patient_last_name %></td>
            <!--<td><%= link_to t('button.continue'), patient_enrol_path(patient), :class => "btn btn-info btn-xs" %></td>-->
            <td><%= link_to t('button.continue'), edit_polymorphic_url([patient, patient.enrollable]), :class => "btn btn-info btn-xs" %></td>
            <td><%= link_to t('pages.home.view'), patient, :class => "btn btn-info btn-xs" %></td>
          </tr>
      <% else %>
          <tr>
            <td><%= patient.registrant_first_name %></td>
            <td><%= patient.registrant_last_name %></td>
            <td>
              <% if patient.relation_to_patient %>
                  <%= Patient.applicant_relation_collection[patient.relation_to_patient][0] %>
              <% end %>
            </td>
            <td><%= patient.patient_first_name %></td>
            <td><%= patient.patient_last_name %></td>
            <td><%= link_to t('pages.home.enrol'), patient_enrol_path(patient), :class => "btn btn-info btn-xs" %></td>
            <td><%= link_to t('pages.home.view'), patient, :class => "btn btn-info btn-xs" %></td>
          </tr>
      <% end %>
  <% end %>

  </tbody>

</table>

<h2><%= t 'pages.home.enrol_table_title' %></h2>
<table class='table table-condensed table-bordered table-striped'>
  <thead>
  <tr>
    <th class="col-md-1"><%= t 'pages.home.table_patient_id' %></th>
    <th class="col-md-1"><%= t 'pages.home.verified' %></th>
    <th class="col-md-1"><%= t 'patients.labels.enrolment_form' %></th>
    <th class="col-md-1"><%= t 'pages.home.complete_follow_up_num' %></th>
    <th class="col-md-1"></th>
    <th class="col-md-1"></th>
  </tr>
  </thead>
  <tbody>
  <% @user.patients.each do |patient| %>
      <% next unless (patient.enrollable && !patient.enrollable.not_finish?) %>
      <tr>
        <td><%= patient.get_unique_id %></td>
        <td><%= patient.verified ? "<span class='glyphicon glyphicon-ok verified'>".html_safe : "<span class='glyphicon glyphicon-remove unverified'>".html_safe %></td>
        <td><%= link_to t('pages.home.view'), patient, :class => "btn btn-info btn-xs" %></td>
        <td><%= patient.enrollable.followup_count %></td>
        <% if patient.enrollable.followup_class %>
            <td><%= link_to t('patients.buttons.questionnaires'), polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => "btn btn-info btn-xs #{patient.verified ? '' : 'disabled'}" %></td>
        <% else %>
            <td><%= link_to 'In development', polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => 'btn btn-danger btn-xs disabled' %></td>
        <% end %>
        <% if patient.enrollable.followup_class %>
            <td><%= link_to t('patients.buttons.new_questionnaires'), new_polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => "btn btn-info btn-xs #{patient.verified ? '' : 'disabled'} #{patient.enrollable.lock_new_questionnaire ? 'disabled' : ''}" %></td>
        <% else %>
            <td><%= link_to 'In development', new_polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => 'btn btn-danger btn-xs disabled' %></td>
        <% end %>

      </tr>

  <% end %>
  </tbody>

</table>


<div class="form-actions pull-left">
  <%= link_to t('pages.home.add_patient_button'), new_patient_path, :class => 'btn btn-primary' %>
</div>
<br>
<br>
<hr>
<% if @user.study_team %>
    <h2><%= t 'pages.home.unverified_table_title' %> <strong>(Admin)</strong></h2>
    <table class='table table-condensed table-bordered table-striped'>
      <thead>
      <tr>
        <th class="col-md-1"><%= t 'pages.home.table_patient_id' %></th>
        <th class="col-md-1"><%= t 'pages.home.complete' %></th>
        <th class="col-md-1"><%= t 'pages.home.verified' %></th>
        <th class="col-md-1"><%= t 'patients.labels.enrolment_form' %></th>
        <th class="col-md-1"><%= t 'pages.home.complete_follow_up_num' %></th>
        <th class="col-md-1"></th>
      </tr>
      </thead>
      <tbody>
      <% @all_patients.each do |patient| %>
          <% next unless patient.enrollable %>
          <tr>
            <td><%= patient.get_unique_id %></td>
            <td><%= patient.enrollable.not_finish? ? "<span class='glyphicon glyphicon-remove incompleted'>".html_safe : "<span class='glyphicon glyphicon-ok completed'>".html_safe %></td>
            <td><%= patient.verified ? "<span class='glyphicon glyphicon-ok verified'>".html_safe : "<span class='glyphicon glyphicon-remove unverified'>".html_safe %></td>
            <td><%= link_to t('pages.home.view'), patient, :class => "btn btn-info btn-xs" %></td>
            <td><%= patient.enrollable.followup_count %></td>
            <% if patient.enrollable.followup_class %>
                <td><%= link_to t('patients.buttons.questionnaires'), polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => "btn btn-info btn-xs #{patient.verified ? '' : 'disabled'}" %></td>
            <% else %>
                <td><%= link_to 'In development', polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => 'btn btn-danger btn-xs disabled' %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>

    </table>

<% end %>

INPDR-Server_withAPI/app/views/patients/new.html.erb
<%= render 'form' %>

<div class="form-actions pull-right">
  <%= link_to 'Cancel', :back, :class => 'btn btn-danger' %>
</div>

INPDR-Server_withAPI/app/views/patients/show.html.erb
<div id='section-to-print'>
  <% unless @patient.verified? %>

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t '.title' %></h3>
        </div>
        <div class="panel-body">

          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.registrant_first_name" %>
            </div>
            <div class="form-applicant_show-content">
              <%= @patient.registrant_first_name %>
            </div>
          </div>
          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.registrant_last_name" %>
            </div>
            <div class="form-applicant_show-content">
              <%= @patient.registrant_last_name %>
            </div>
          </div>

          <div class="participant-show-form-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= t 'patients.labels.address' %></h3>
              </div>
              <div class="panel-body">
                <%= render :partial => 'layouts/show_address_fields', :locals => {:address => @patient.address} %>
              </div>
            </div>
          </div>

          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.relation_to_patient" %>
            </div>
            <div class="form-applicant_show-content">
              <% if @patient.relation_to_patient %>
                  <%= Patient.applicant_relation_collection[@patient.relation_to_patient][0] %>
              <% end %>
            </div>
          </div>
          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.patient_first_name" %>
            </div>
            <div class="form-applicant_show-content">
              <%= @patient.patient_first_name %>
            </div>
          </div>
          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.patient_last_name" %>
            </div>
            <div class="form-applicant_show-content">
              <%= @patient.patient_last_name %>
            </div>
          </div>
          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.gender" %>
            </div>
            <div class="form-applicant_show-content">
              <% if @patient.gender %>
                  <%= Patient.gender_collection[@patient.gender][0] %>
              <% end %>
            </div>
          </div>
          <div class="participant-show-form-group">
            <div class="form-applicant_show-label">
              <%= t "#{controller_name}.labels.date_of_birth" %>
            </div>
            <div class="form-applicant_show-content">
              <%= @patient.date_of_birth %>
            </div>
          </div>

          <div class="participant-show-form-group">
            <%= render :partial => 'layouts/specialist_fields_show', :locals => {:specialist => @patient.specialist} %>
          </div>
        </div>
      </div>
  <% end %>

  <% if @patient.enrollable %>
  <% if ((@patient.enrollable.is_a? NpcApplicantParticipant) || (@patient.enrollable.is_a? NpcParticipant)) %>

      <%= render 'layouts/npc_enrol_info_show', :participant => @patient.enrollable %>
  <% end %>

  <% if ((@patient.enrollable.is_a? NpbApplicantParticipant) || (@patient.enrollable.is_a? NpbParticipant)) %>
      <%= render 'layouts/npb_enrol_info_show', :participant => @patient.enrollable %>
  <% end %>

  <% if (@patient.enrollable.is_a? NpaApplicantParticipant) %>
      <%= render 'layouts/npa_enrol_info_show', :participant => @patient.enrollable %>
  <% end %>



  <%= render 'layouts/gene_diagnosis_show', :participant => @patient.enrollable %>
  <% end %>
  <%= render 'layouts/consent_fields_show', :participant => @patient %>

</div>


<%= link_to 'Back', :back, :class => 'btn btn-default' %>

<% if current_user.study_team && @patient.enrollable && !@patient.enrollable.not_finish? %>
    <% if @patient.verified %>
        <%= link_to 'Verified', [:verify, @patient], :class => 'btn btn-success disabled' %>
    <% else %>
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
          Verify
        </button>
    <% end %>
<% end %>

<%= render 'layouts/confirm_verification_modal' %>