INPDR-Server_withAPI/config/routes.rb
Rails.application.routes.draw do

  mount API::Base => "/"

  match '/contacts', :to => 'contacts#new', :via => 'get'
  resources :contacts, :only => [:new, :create]

  devise_for :users, :controllers => {:registrations => :registrations}

  root :to => 'pages#index'

  get 'pages/index'
  get 'pages/registration'
  get 'pages/terms_and_conditions'
  get 'pages/privacy_statement'
  get 'pages/followups'
  get 'pages/verifications'
  get 'pages/thank_enrol'

  post 'patients/consent_action', to: 'patients#consent_action'
  resources :patients do
    get 'enrol'
    get 'verify', :on => :member
    resources :npa_applicant_participants do
    end

    resources :npb_participants do
      resources :npb_followups, :defaults => {:followable => 'npb_participants'}
    end

    resources :npb_applicant_participants do
      resources :npb_followups, :defaults => {:followable => 'npb_applicant_participants'}
    end

    resources :npc_applicant_participants do
      resources :npc_followups, :defaults => {:followable => 'npc_applicant_participants'}
    end

    resources :npc_participants do
      resources :npc_followups, :defaults => {:followable => 'npc_participants'}
    end
  end

end

INPDR-Server_withAPI/app/views/pages/followups.html.erb
  <h1><%= t '.title' %></h1>

  <h2><%= t 'pages.home.enrol_table_title' %></h2>
  <table class='table table-condensed table-bordered table-striped'>
    <thead>
    <tr>
      <th class="col-md-2"><%= t 'pages.home.table_patient_id' %></th>
      <th class="col-md-1"></th>
      <th class="col-md-2"><%= t 'pages.home.complete_follow_up_num' %></th>
      <th class="col-md-1"></th>
    </tr>
    </thead>
    <tbody>
    <% @user.patients.each do |patient| %>
        <% next unless (patient.enrollable && patient.verified) %>
        <tr>
          <td><%= patient.get_unique_id %></td>
          <td><%= link_to t('pages.home.view'), patient, :class => "btn btn-info btn-xs" %></td>
          <td><%= patient.enrollable.followup_count %></td>
          <% if patient.enrollable.followup_class %>
              <td><%= link_to t('pages.home.complete_follow_up'), polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => "btn btn-info btn-xs #{patient.verified ? '' : 'disabled'}" %></td>
          <% else %>
              <td><%= link_to 'In development', polymorphic_url([patient, patient.enrollable, patient.enrollable.followup_class]), :class => 'btn btn-danger btn-xs disabled' %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>

  </table>

INPDR-Server_withAPI/app/views/pages/index.html.erb
<div class="center jumbotron">
  <h1><%= t 'index.title' %></h1>

  <p>Niemann Pick Diseases (NPD) are rare, progressive conditions with many unanswered questions. More information is
    needed to better understand how they affect people and progress over time. The International Niemann Pick Disease
    Registry (INPDR) – a joint initiative between patient organisations and clinicians involved in the care of people
    with NPD – was established to better understand NPD so that potential treatments can be developed as quickly as
    possible.</p>

  <p>There are two components to the INPDR, together collecting clinical, genetic, diagnostic and outcome data: patient
    reported data (PRD), completed by the patient or their carer if appropriate; and clinician reported data (CRD),
    completed by healthcare professionals caring for NPD patients. </p>

  <p>You can confidentially record health information in the patient-reported section of the INPDR. Only anonymous
    health information will be made accessible to qualified researchers who are granted permission by the Steering
    committee. Personal health information will not be made available to employers, government organisations,
    insurance companies, or educational institutions. Please refer to
    the <%= link_to 'Privacy Policy', pages_privacy_statement_path %> for more
    information. </p>

  <p>We welcome all patients diagnosed with any type of NPD worldwide. Patients can participate in the registry
    regardless of whether or not they are involved in other clinical studies and trials. </p>

  <p><strong>If you are registering more than one person</strong>, you may use the same login and password to enter
    multiple patients. However, a separate survey must be completed for each person. This can be done after registering
    by clicking "Add a new patient" from your log in page.</p>

  <p>Please feel free to share any questions or concerns with us! You can contact the INPDR team at
    <a href="mailto:inpdr@uhb.nhs.uk" target="_top">inpdr@uhb.nhs.uk</a></p>

  <p>Thank you for taking the time to complete this information and assist in our efforts to improve the lives of those
    living with Niemann-Pick Diseases. </p>

  <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-lg btn-primary" %>
  <%= link_to t('main_header.login'), new_user_session_path, :class => "btn btn-lg btn-primary" %>
</div>

INPDR-Server_withAPI/app/views/pages/privacy_statement.html.erb
<div class='well'>
<h1>Privacy and Data protection</h1>

<h2>Where will my data be stored?</h2>
<p>All electronic data generated from the PRD will be held at the University of Melbourne, Australia under the direct
  responsibility of the Director of eResearch, Professor Richard Sinnott. Your data will be stored securely and no
  unauthorized users will be able to gain access to any information about you. Patient Identifiable Information that is
  required for patient sign up will be kept in the Registry Master File which is securely held at the Queen Elizabeth
  Hospital Birmingham, UK, under the responsibility of Dr Tarekegn Hiwot. Patient Identifiable Information will not be
  held on the PRD itself.</p>

<h2>Who will have access to my medical records?</h2>
<p>Only PRD staff members will have access to your medical records. PRD staff members may be required to obtain access
  to your genetic diagnosis report from your medical records in order to find information necessary for your involvement
  in the Registry. Access to your medical records will be on your behalf, and will only occur if you have given approval
  for PRD staff to do so. </p>

<h2>How will I be identified in the registry?</h2>
<p>Your patient identifiable information (name, address etc.) will be securely held in the Registry Master File so that
  PRD staff members can contact you if it is necessary to inform you about your participation in the PRD.</p>
<p>This information will be stored in a secure manner and your records will be assigned a unique ID. This unique ID will
  be used to identify your records. Authorised staff that uses the Registry will not be able to identify you personally
  from the information. Only the individual in charge of the Registry (Dr Tarekegn Hiwot) and persons explicitly
  appointed to the Registry team by Dr Hiwot will be able to link your unique ID to your personal information.</p>

<h2>Will my data be kept confidential?</h2>
<p>All electronic data generated from the PRD will be held at the University of Melbourne, Australia under the direct
  responsibility of the Director of eResearch, Professor Richard Sinnott. The Register Master File will be held securely
  at the Queen Elizabeth Hospital Birmingham, UK, under the responsibility of Dr Tarekegn Hiwot</p>
<p>The Registry team have direct experience in working to UK and international standards (including ISO 17799, and US 21
  CFR part 11), and have extensive experience of using healthcare data in the context of privacy and data protection
  legislature (including the Data Protection Act 1998 and EU Data Protection Directive 95/46/EC). </p>
<p>In order for third parties (such as researchers, clinical research companies, pharmaceutical companies etc) to access
  data held in the registry, they must meet the strict requirements laid out by the Registry management committee,
  including having ethics committee approval. Approved third parties will only have access to anonymous information
  identifiable by a code. Your data will <b>not be made available</b> to employers, government organisations, insurance
  companies or educational institutions.</p>

<h2>Can I withdraw from the registry and have my data destroyed?</h2>
<p>Your participation in this project is completely voluntary, and as such you are free to withdraw from the registry at
  any time. Should you wish to withdraw, you are not required to offer a reason why. All data generated will be securely
  destroyed and you will not be contacted in regards to the registry. If you wish to withdraw, you should contact
  inpdr@uhb.nhs.uk.</p>
    </div>

INPDR-Server_withAPI/app/views/pages/registration.html.erb
<div class="center jumbotron">
  <blockquote>
    <h1><%= t '.title' %></h1>

    <p>
      Your registration is now being processed. We will be in touch via email as soon as possible with your user name
      and password. You will then be able to log into the registry and complete the patient reported questionnaires.
    </p>

    <p>
      In the meantime, if you have any questions at all you can contact us at
      <a href="mailto:inpdr@uhb.nhs.uk" target="_top">inpdr@uhb.nhs.uk</a>. And
      again, THANK YOU for your involvement.
    </p>
  </blockquote>
  <blockquote class="blockquote-reverse">
    <footer>From the INPDR team</footer>
  </blockquote>
</div>

INPDR-Server_withAPI/app/views/pages/terms_and_conditions.html.erb
<div class='well'>

  <h2>Section 1. Terms and Conditions</h2>

  <ul>
    <li>The International Niemann-Pick Disease Patient Reported Dataset Registry is a web-based tool produced as a
      collaborative effort between partners within the International Niemann-Pick Disease Registry consortium. As used
      in this Terms and Conditions, the term "INPDR" shall mean "International Niemann-Pick Disease Registry
      Consortium" and the term "INPD-PRD" shall mean "International Niemann-Pick Disease Patient Reported Dataset
      Registry". By using the INPD-PRD, this constitutes your agreement to be bound to these Terms and Conditions. If
      you do not agree to the Terms and Conditions, you may not use the INPD-PRD.
    </li>
  </ul>

  <h2>Section 2. Use of Services</h2>
  <ul>
    <li>NOT FOR EMERGENCIES OR MEDICAL OR PROFESIONAL ADVICE</li>
    <ul>
      <li>The INPD-PRD does not provide any medical or healthcare products, services or advice, and is not for medical
        emergencies or urgent situations. IF YOU THINK YOU MAY HAVE A MEDICAL EMERGENCY, CONTACT YOUR LOCAL EMERGENCY
        NUMBER OR CONTACT YOUR DOCTOR IMMEDIATELY. Additionally, information contained on this website is not a
        substitute for a doctor's medical judgment or advice. INPD-PRD recommends that you discuss your specific,
        individual health issues and concerns with your doctor or healthcare professional. The services offered and
        information contained on the INPD-PRD are designed to help us better understand the natural history of NPD and
        to foster future research.
      </li>
    </ul>
    <li>Cost</li>
    <ul>
      <li>There is no cost for enrolling into and using the INPD-PRD.</li>
    </ul>
    <li>Your Account</li>
    <ul>
      <li>Upon your consent being approved by the INPD-PRD study team, you will be provided with a unique patient
        identifier and password. You are solely responsible for maintaining the confidentiality of your unique patient
        identifier and password and for all activities that occur under your username and password. You must not
        provide your unique patient identifier and password to anybody else and should immediately notify the INPD-PRD
        study team of any unauthorized use of your patient identifier and password or other security concerns of which
        you may have.
      </li>
      <li>You agree that the INPD-PRD study team may access, preserve, and disclose your account information,
        including your username and password, if required to do so by law or in good faith belief that it is necessary
        to: (i) enforce this Terms and Conditions, (ii) respond to your requests for customer service, (iii) comply
        with laws or legal process, (iv) respond to claims that information you have provided violates the rights of
        others, or (v) protect the rights, property or personal safety of INPD-PRD and its users or the public. You
        confirm that you are at least eighteen years of age, and that you possess the legal right and ability to enter
        into this Terms and Conditions and abide by the obligations hereunder.
      </li>
    </ul>
    <li>Intellectual Property</li>
    <ul>
      <li>With the exception of any personal information submitted by a potential research volunteer, INPDR retains
        all right, title and interest in and to the INPD-PRD website, the INPD-PRD services and any content, products,
        documentation, or other materials on the INPD-PRD website. INPD-PRD website must be firstly agreed with the
        INPDR. You agree not to reproduce, sell, publish, or circulate the information owned by INPD-PRD, or received
        from any other party or individual through the INPD-PRD website or registry to anyone.
      </li>
    </ul>
    <li>Third Party Sites</li>
    <ul>
      <li>Although INPD-PRD may include links providing direct access to third-party Internet sites, NPD-PRD takes no
        responsibility for the content or information contained on those other sites.
      </li>
    </ul>
    <li>Operation and Record Retention</li>
    <ul>
      <li>INPD-PRD may withdraw, suspend or discontinue any functionality or feature of INPD-PRD features or services.
        INPD-PRD is not responsible for transmission errors or corruption or compromise of data. INPD-PRD reserves the
        right to maintain, delete or destroy materials uploaded to INPD-PRD.
      </li>
    </ul>
    <li>Limitations on Use</li>
    <ul>
      <li>You agree not to access or use the INPD-PRD website in an unlawful way. You agree not to transmit: (a)
        information under a false name; or (b) any information which (i) is fraudulent, false or contrary to the
        ownership or intellectual property rights of any other person, or (ii) contains any virus, worm, Trojan horse
        or other code which is contaminating or destructive to the files or programs of INPD-PRD or any of its users.
        INPD-PRD reserves the right to delete any information provided by you that it deems in its sole discretion
        fraudulent, false, contrary or in violation of the ownership rights of any other person.
      </li>
    </ul>
  </ul>
  <h2>Section 3. Disclaimers</h2>
  <ul>
    <li>General Disclaimers</li>
    <ul>
      <li>You acknowledge that your use of the INPD-PRD website is at your sole risk, and that you assume full
        responsibility for all risk associated therewith
      </li>
    </ul>
    <li>Limitation of Liability</li>
    <ul>
      <li>In no event shall INPD-PRD or INPDR be liable for any damages or other liability to you or any other users of
        the INPD-PRD website.
      </li>
    </ul>
  </ul>
  <h2>Section 4. General Provisions</h2>
  <ul>
    <li>Indemnity</li>
    <ul>
      <li>You agree to indemnify, defend and hold harmless INPD-PRD, INPDR and its affiliates from and against all
        losses, liability, expenses, damages and costs, arising out of or related to any breach of this terms and
        conditions, any negligent or wrongful action or omission by you related to your use of or providing of services
        through the INPD-PRD website, or any negligent or wrongful use of the INPD-PRD website by you or any other
        person accessing your account.
      </li>
    </ul>
    <li>Governing Law</li>
    <ul>
      <li>This Terms and Conditions shall be governed by and construed in accordance with the laws of England without
        giving effect to any choice of law rules or principles. You agree that Birmingham, England shall be the sole and
        exclusive venue for any legal action or proceeding between INPD-PRD or INPDR and you for any purpose concerning
        this Terms and Conditions. Any cause of action or claim you may have with respect to the use of the INPD-PRD
        website must be commenced within one (1) year after it arises, except to the extent such limitation is not
        enforceable.
      </li>
    </ul>
    <li>Changes to Terms and Conditions</li>
    <ul>
      <li>INPD-PRD reserves the right to update or change these Terms and Conditions at any time and for any reason by
        posting the modified Terms and Conditions. You should periodically visit this page of the website. All Terms and
        Conditions are automatically effective as soon as they are posted.
      </li>
    </ul>
  </ul>

  <p>Thank you for reading the INPD-PRD Terms and Conditions</p>
</div>

INPDR-Server_withAPI/app/views/pages/thank_enrol.html.erb
<div class="center jumbotron">
  <blockquote>
    <h1><%= t '.title' %></h1>

    <p>
      Your enrolment details are now being processed. We will be in touch via email as soon as possible to confirm your
      registration. You will then be asked to log into the registry and complete the patient reported questionnaires.
    </p>

    <p>
      In the meantime, if you have any questions at all you can contact us at
      <a href="mailto:inpdr@uhb.nhs.uk" target="_top">inpdr@uhb.nhs.uk</a>. And
      again, THANK YOU for your involvement.
    </p>
  </blockquote>
  <blockquote class="blockquote-reverse">
    <footer>From the INPDR team</footer>
  </blockquote>
</div>

INPDR-Server_withAPI/app/views/pages/verifications.html.erb
<div class="center jumbotron">
  <h1><%= t '.title' %></h1>

  <div class="list-group">
    <a href="<%=  npc_participants_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npc_title') %></h4>

    </a>
    <a href="<%=  npc_applicant_participants_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npc_behalf_title') %></h4>

    </a>
    <a href="<%=  npb_participants_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npb_title') %></h4>

    </a>
    <a href="<%=  npb_applicant_participants_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npb_behalf_title') %></h4>

    </a>
    <a href="<%=  npa_applicant_participants_path %>" class="list-group-item">
      <h4 class="list-group-item-heading"><%= t('.npa_title') %></h4>

    </a>
  </div>

</div>