INPDR-Server_withAPI/config/routes.rb
Rails.application.routes.draw do

  mount API::Base => "/"

  match '/contacts', :to => 'contacts#new', :via => 'get'
  resources :contacts, :only => [:new, :create]

  devise_for :users, :controllers => {:registrations => :registrations}

  root :to => 'pages#index'

  get 'pages/index'
  get 'pages/registration'
  get 'pages/terms_and_conditions'
  get 'pages/privacy_statement'
  get 'pages/followups'
  get 'pages/verifications'
  get 'pages/thank_enrol'

  post 'patients/consent_action', to: 'patients#consent_action'
  resources :patients do
    get 'enrol'
    get 'verify', :on => :member
    resources :npa_applicant_participants do
    end

    resources :npb_participants do
      resources :npb_followups, :defaults => {:followable => 'npb_participants'}
    end

    resources :npb_applicant_participants do
      resources :npb_followups, :defaults => {:followable => 'npb_applicant_participants'}
    end

    resources :npc_applicant_participants do
      resources :npc_followups, :defaults => {:followable => 'npc_applicant_participants'}
    end

    resources :npc_participants do
      resources :npc_followups, :defaults => {:followable => 'npc_participants'}
    end
  end

end

INPDR-Server_withAPI/app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Contact from INPDR Registration",
        :to => "info@inpda.org",
        :from => %("#{name}" <#{email}>)
    }
  end
end

INPDR-Server_withAPI/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to root_path, notice: 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.fetch(:contact, {})
    end
end

INPDR-Server_withAPI/app/helpers/contacts_helper.rb
module ContactsHelper
end

INPDR-Server_withAPI/app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

INPDR-Server_withAPI/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

INPDR-Server_withAPI/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

INPDR-Server_withAPI/app/views/contacts/new.html.erb
<h2><%= t('pages.contacts.title') %></h2>
<div class='well'>
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal'} do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class="hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
        <%= f.button :submit, 'Send message', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>

INPDR-Server_withAPI/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>